# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-03 19:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gettrafficlights', '0003_auto_20170703_2107'),
    ]

    operations = [
    ]
