# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-06 11:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gettrafficlights', '0004_auto_20170705_1619'),
        ('gettrafficlights', '0004_auto_20170703_2109'),
    ]

    operations = [
    ]
