# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-06 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='err',
            field=models.CharField(default=3, max_length=20),
            preserve_default=False,
        ),
    ]
