# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-06 11:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('Key', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('lon', models.CharField(max_length=20)),
                ('lat', models.CharField(max_length=20)),
            ],
        ),
    ]
