# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-04 17:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contains',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('National_ID', models.CharField(max_length=5)),
                ('First_Name', models.CharField(max_length=250)),
                ('Last_Name', models.CharField(max_length=250)),
                ('Username', models.CharField(max_length=25)),
                ('Encrypted_Password', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='EmergencyVehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Car_ID', models.CharField(max_length=10)),
                ('Type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Intersection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Intersection_ID', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Street',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Street_ID', models.CharField(max_length=5)),
                ('Start_Longitude', models.CharField(max_length=25)),
                ('Start_Latitude', models.CharField(max_length=25)),
                ('End_Longitude', models.CharField(max_length=25)),
                ('End_Latitude', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='TrafficLight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TL_ID', models.CharField(max_length=5)),
                ('Longitude', models.CharField(max_length=25)),
                ('Latitude', models.CharField(max_length=25)),
                ('Direction', models.CharField(max_length=2)),
                ('Intersection_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gettrafficlights.Intersection')),
            ],
        ),
        migrations.CreateModel(
            name='Use',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Car_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gettrafficlights.EmergencyVehicle')),
                ('National_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gettrafficlights.Driver')),
            ],
        ),
        migrations.AddField(
            model_name='contains',
            name='Intersection_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gettrafficlights.Intersection'),
        ),
        migrations.AddField(
            model_name='contains',
            name='Street_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gettrafficlights.Street'),
        ),
    ]
