# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-17 00:04
from __future__ import unicode_literals

from django.db import migrations, models
import gettrafficlights.models


class Migration(migrations.Migration):

    dependencies = [
        ('gettrafficlights', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trafficlight',
            name='TL_ID',
            field=models.IntegerField(default=gettrafficlights.models.TL_number, primary_key=True, serialize=False),
        ),
    ]
