# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-04 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gettrafficlights', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='id',
        ),
        migrations.RemoveField(
            model_name='emergencyvehicle',
            name='id',
        ),
        migrations.RemoveField(
            model_name='intersection',
            name='id',
        ),
        migrations.RemoveField(
            model_name='street',
            name='id',
        ),
        migrations.RemoveField(
            model_name='trafficlight',
            name='id',
        ),
        migrations.AlterField(
            model_name='driver',
            name='Encrypted_Password',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='driver',
            name='National_ID',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='emergencyvehicle',
            name='Car_ID',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='intersection',
            name='Intersection_ID',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='street',
            name='End_Latitude',
            field=models.FloatField(max_length=25),
        ),
        migrations.AlterField(
            model_name='street',
            name='End_Longitude',
            field=models.FloatField(max_length=25),
        ),
        migrations.AlterField(
            model_name='street',
            name='Start_Latitude',
            field=models.FloatField(max_length=25),
        ),
        migrations.AlterField(
            model_name='street',
            name='Start_Longitude',
            field=models.FloatField(max_length=25),
        ),
        migrations.AlterField(
            model_name='street',
            name='Street_ID',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='trafficlight',
            name='Latitude',
            field=models.FloatField(max_length=25),
        ),
        migrations.AlterField(
            model_name='trafficlight',
            name='Longitude',
            field=models.FloatField(max_length=25),
        ),
        migrations.AlterField(
            model_name='trafficlight',
            name='TL_ID',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
