# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 16:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gettrafficlights', '0001_initial'),
    ]

    operations = [
    ]
