# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 19:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gettrafficlights', '0002_auto_20170630_1816'),
    ]

    operations = [
    ]
