# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-17 00:07
from __future__ import unicode_literals

from django.db import migrations, models
import gettrafficlights.models


class Migration(migrations.Migration):

    dependencies = [
        ('gettrafficlights', '0002_auto_20170617_0204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centralnode',
            name='CentralNode_ID',
            field=models.CharField(default=gettrafficlights.models.Central_Node_number, max_length=25, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='intersection',
            name='Intersection_ID',
            field=models.CharField(default=gettrafficlights.models.Intersection_number, max_length=25, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='trafficlight',
            name='TL_ID',
            field=models.CharField(default=gettrafficlights.models.TL_number, max_length=25, primary_key=True, serialize=False),
        ),
    ]
