# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-11 19:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gettrafficlights', '0003_auto_20161204_1918'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntersectionsStreets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Intersection_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gettrafficlights.Intersection')),
            ],
        ),
        migrations.RemoveField(
            model_name='emergencyvehicle',
            name='Type',
        ),
        migrations.RemoveField(
            model_name='street',
            name='Intersection_ID',
        ),
        migrations.AddField(
            model_name='emergencyvehicle',
            name='Priority',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='driver',
            name='Encrypted_Password',
            field=models.CharField(max_length=25),
        ),
        migrations.AddField(
            model_name='intersectionsstreets',
            name='Street_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gettrafficlights.Street'),
        ),
    ]
