# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 14:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gettrafficlights', '0003_auto_20170705_1619'),
    ]

    operations = [
    ]
