# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-24 20:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gettrafficlights', '0004_auto_20161211_2146'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='driver',
            options={'permissions': (('is_driver', 'Permission for drivers'),)},
        ),
        migrations.AddField(
            model_name='driver',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
