# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-24 00:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gettrafficlights', '0004_auto_20161211_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='intersection',
            name='IP',
            field=models.CharField(default='0', max_length=8),
        ),
        migrations.AlterField(
            model_name='intersection',
            name='Intersection_ID',
            field=models.CharField(max_length=12, primary_key=True, serialize=False),
        ),
    ]
