# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-20 19:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gettrafficlights', '0004_auto_20161211_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='intersection',
            name='Intersection_IP',
            field=models.CharField(default='000.000.000.000', max_length=15),
        ),
        migrations.AlterField(
            model_name='trafficlight',
            name='TL_ID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
