# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-24 13:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gettrafficlights', '0005_auto_20170124_0202'),
    ]

    operations = [
        migrations.AddField(
            model_name='intersection',
            name='MAC',
            field=models.CharField(default=b'0', max_length=12),
        ),
        migrations.AlterField(
            model_name='intersection',
            name='Intersection_ID',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='street',
            name='Street_ID',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
