# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-20 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gettrafficlights', '0005_auto_20161220_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intersection',
            name='Intersection_ID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
