# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-15 18:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gettrafficlights', '0005_auto_20170615_2018'),
    ]

    operations = [
    ]
