# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-24 21:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gettrafficlights', '0006_auto_20170124_2253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='Encrypted_Password',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='First_Name',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='Last_Name',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='Username',
        ),
    ]
