# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-25 11:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gettrafficlights', '0007_auto_20170124_2305'),
        ('gettrafficlights', '0006_auto_20170124_1546'),
    ]

    operations = [
    ]
